=== OpenCerts/open-certificate/schema/1.2/schema.json
{
  "$id": "opencerts/v1.2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "$template": {
      "type": "string"
    },
    "issuedOn": {
      "type": "string",
      "format": "date-time",
      "examples": ["2018-08-01T00:00:00+08:00"]
    },
    "expiredOn": {
      "type": "string",
      "format": "date-time"
    },
    "admissionDate": {
      "type": "string",
      "format": "date-time"
    },
    "graduationDate": {
      "type": "string",
      "format": "date-time"
    },
    "cumulativeScore": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "issuers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "did": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "url"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phone": {
            "type": "string"
          },
          "certificateStore": {
            "type": "string"
          }
        },
        "required": ["name", "certificateStore"],
        "additionalProperties": false
      },
      "exampples": [
        {
          "name": "Blockchain Academy",
          "did": "DID:SG-UEN:U18274928E",
          "url": "https://blockchainacademy.com",
          "email": "registrar@blockchainacademy.com",
          "certificateStore": "0xd9580260be45c3c0c2fb259a82f219b513054012"
        }
      ]
    },
    "recipient": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "did": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        }
      },
      "required": ["name"],
      "additionalProperties": false
    },
    "transcript": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "score": {
            "type": ["number", "string"]
          },
          "grade": {
            "type": ["number", "string"]
          },
          "courseCredit": {
            "type": ["number", "string"]
          },
          "courseCode": {
            "type": "string"
          },
          "examinationDate": {
            "type": "string",
            "format": "date-time"
          },
          "url": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": ["name"],
        "additionalProperties": false
      }
    },
    "additionalData": {
      "type": "object"
    }
  },
  "required": ["$schema", "id", "name", "issuedOn", "issuers", "recipient"],
  "additionalProperties": false
}

=== OpenCerts/open-certificate/schema/1.2/example.json
{
  "id": "SERIAL-2018-08-01-112",
  "$schema": "https://govtechsg.github.io/open-certificate/schema/1.2/schema.json",
  "$template": "BLOCKCHAIN-ACADEMY-2018-001",
  "issuedOn": "2018-08-01T00:00:00+08:00",
  "expiredOn": "2118-08-01T00:00:00+08:00",
  "name": "Master of Blockchain",
  "admissionDate": "2017-08-01T00:00:00+08:00",
  "graduationDate": "2018-08-01T00:00:00+08:00",
  "issuers": [
    {
      "name": "Blockchain Academy",
      "did": "DID:SG-UEN:U18274928E",
      "url": "https://blockchainacademy.com",
      "email": "registrar@blockchainacademy.com",
      "certificateStore": "0xd9580260be45c3c0c2fb259a82f219b513054012"
    }, 
    {
      "name": "School of Crypto-economics",
      "url": "https://ceschool.sg",
      "certificateStore": "0xA33ddAEE02369D18A21E29dD2E7A12d65eE671d2"
    }
  ],
  "recipient": {
    "name": "Mr Blockchain",
    "did": "DID:SG-NRIC:S99999999A",
    "email": "mr-blockchain@gmail.com",
    "phone": "+65 88888888"
  },
  "transcript": [
    {
      "name": "Bitcoin",
      "grade": "A+",
      "courseCredit": 3,
      "courseCode": "BTC-01",
      "examinationDate": "2018-08-01T00:00:00+08:00",
      "url": "https://blockchainacademy.com/subject/BTC-01",
      "description": "Everything and more about bitcoin!"
    },
    {
      "name": "Ethereum",
      "grade": "A+",
      "courseCredit": "3.5",
      "courseCode": "ETH-01",
      "examinationDate": "2018-08-01T00:00:00+08:00",
      "url": "https://blockchainacademy.com/subject/ETH-01",
      "description": "Everything and more about ethereum!"
    }
  ],
  "cumulativeScore": 3.9935,
  "additionalData": {
    "coCurricularActivities": [
      {
        "name": "Crypto-investment Club",
        "position": "Club President",
        "startDate": "2017-08-01T00:00:00+08:00",
        "endDate": "2018-08-01T00:00:00+08:00",
        "remarks": "Top trader (2018)"
      }
    ],
    "npfa": "silver",
    "images": {
      "signature1": {
        "name": "Mr Important",
        "designation": "President",
        "signature": "<-- Base64 Image -->"
      },
      "signature2": {
        "name": "Mr Not-So-Important",
        "designation": "Chairman, Blockchain Faculty",
        "signature": "<-- Base64 Image -->"
      }
    }
  }
}
